scripts/pipelines: Create script for building meta-toolchain
ni/nilrt pull request #197
Opened 2022-11-02 17:48 UTC by mike-petersen-ni

This creates a simple script to easily allow building of the cross-compile toolchain, similar to the other scripts used for pipelines.

Note: running the build may be dependent on ni/meta-nilrt#494.

AB#1242721

2022-11-02 17:59 UTC, shruthi-ravi requested changes

2022-11-02 17:59 UTC, shruthi-ravi commented on scripts/pipelines/build.toolchain-feeds.sh
> +#!/bin/bash
Should the name of the script be just `build.toolchain`? I don't think we need the `feeds`.

2022-11-02 18:09 UTC, mike-petersen-ni commented on scripts/pipelines/build.toolchain-feeds.sh
> +#!/bin/bash
I'm fine with that. Will be in the next push.

2022-11-02 18:15 UTC, shruthi-ravi approved these changes

2022-11-03 18:35 UTC, amstewart approved these changes

2022-11-03 18:35 UTC, merged