AzDO handles submodules poorly, force an update on all submodules.
ni/nilrt pull request #24
Opened 2020-10-09 21:48 UTC by jeminor

2020-10-09 21:53 UTC, shruthi-ravi approved these changes
Looks good.

2020-10-09 21:53 UTC, shruthi-ravi commented on scripts/azdo/pipeline.yml
> +      git submodule update --remote --checkout
Do you need to include the --init option?

2020-10-09 21:54 UTC, jeminor commented on scripts/azdo/pipeline.yml
> +      git submodule update --remote --checkout
That's a good question, but no (the submodules: true does that much at least).

2020-10-12 17:00 UTC, amstewart requested changes

2020-10-12 17:00 UTC, amstewart commented on scripts/azdo/pipeline.yml
>        source ni-oe-init-build-env
I've pulled the PR which updates this init script with the correct (new) environment variables. Change this source line to [this file](https://github.com/ni/nilrt/blob/nilrt/master/dunfell/nilrt-build-init.env) to populate `NILRT_ROOT`.

2020-11-19 20:49 UTC, amstewart commented
Is this PR still live, @jeminor ?

2021-01-08 18:48 UTC, closed without merging