Update cross-toolchain to produce zip instead of tar.xz
ni/nilrt pull request #279
Opened 2024-07-01 21:09 UTC by usercw88

WI: AB#2788360

Testing:

- [ X ] Executed script locally and verified zip was produced instead of tar.xz

2024-07-01 21:26 UTC, chaitu236 requested changes
In the commit message, we don't usually add WI number but instead describe the changes.

It is enough to mention WI number in PR description which you've already done.

2024-07-01 21:26 UTC, chaitu236 commented on ni-oe-init-build-env
> +export PYREX_CONFIG_BIND="${NILRT_ROOT} ${HOME}/.gitconfig"
We shouldn't add this

2024-07-01 21:31 UTC, chaitu236 commented
> In the commit message, we don't usually add WI number but instead describe the changes.
> 
> It is enough to mention WI number in PR description which you've already done.

PS: Can you also start first line of commit with the filename e.g., https://github.com/ni/nilrt/commit/3680c6a675f3c4366a494a50b44be54e5c321960.

2024-07-01 21:33 UTC, amstewart approved these changes

2024-07-16 15:52 UTC, chaitu236 approved these changes

2024-07-16 16:24 UTC, merged

2024-07-16 16:58 UTC, chaitu236 commented
Cherry-picked to nilrt/master/next